[package]
name = "playground-wasm"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
domain-core  = { path = "../domain-core" }
query-core   = { path = "../query-core" }
serde        = { workspace = true }
serde_json   = { workspace = true }
