{{- if .Values.clickhouse.enabled }}
{{- if .Values.clickhouse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.clickhouse.persistence.storageClass }}
  storageClassName: {{ .Values.clickhouse.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      annotations:
        observable.com/self-observability-mode: {{ .Values.selfObservability.mode | quote }}
        observable.com/self-observability-otlp-endpoint: {{ .Values.selfObservability.otlpEndpoint | quote }}
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.3
          ports:
            - name: http
              containerPort: 8123
            - name: tcp
              containerPort: 9000
          env:
            - name: CLICKHOUSE_DB
              value: {{ .Values.clickhouse.auth.database }}
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.auth.username }}
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.clickhouse.auth.password }}
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          resources:
            {{- toYaml .Values.clickhouse.resources | nindent 12 }}
          {{- if .Values.clickhouse.persistence.enabled }}
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
          {{- end }}
      {{- if .Values.clickhouse.persistence.enabled }}
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: tcp
      port: 9000
      targetPort: 9000
  selector:
    app: clickhouse
{{- end }}
